dedis/onet

- Makefile
- conode.go
- local_test.go
- onet.go
- processor.go
- processor_test.go
- service.go
- websocket.go
- websocket_test.go
> Merge cothority 10

- websocket.go
- websocket_test.go
> implements cothority::737

- websocket.go
> remove signal handling from graceful-server

- context.go
- export_test.go
- local.go
- messages.go
- network/router.go
- network/router_test.go
- overlay.go
- protocol.go
- service.go
- simul/platform/localhost.go
- simul/platform/platform.go
- simul/runsimul.go
- tree.go
- treenode.go
- treenode_test.go
Renaming the few occurences from SDA to onet. Fix #3 .
> Renaming to onet - some left over

- .gitignore
- app/tesht/cothority.sh
- app/tesht/libtest.sh
> added test-libraries for bash

- websocket.go
- websocket_test.go
> webhost server and client

- simul/build.go
- simul/build_test.go
- simul/monitor/monitor.go
- simul/platform/deterlab.go
- simul/platform/localhost.go
- simul/platform/platform.go
- simul/platform/platform_test.go
> no race-condition anymore

- messages.go
- overlay.go
- overlay_test.go
- protocol.go
- protocol_test.go
> changed Message to Msg

- context.go
- context_test.go
- local_test.go
- processor_test.go
- service.go
- service_test.go
- simulation.go
- websocket_test.go
> load save file and memory

- context.go
- context_test.go
> Data available 66

- app/config.go
- app/server.go
> only app-changes

- app/config.go
- app/server.go
- context.go
- context_test.go
- export_test.go
- local.go
- network/struct.go
- overlay.go
- processor_test.go
- protocol.go
- server.go
- server_test.go
- service.go
- service_test.go
- simul/platform/runsimul.go
- simul/simul.go
- simulation.go
- simulation_test.go
- status_test.go
- treenode.go
- websocket.go
- websocket_test.go
> renamed conode to server

- simul/platform/localhost.go
> removing race

- app/commands.go
- app/commands_test.go
- app/libtest.sh
- simul/platform/localhost.go
> Conode server 73

- messages.proto
- network/network.proto
> added proto file

- simul/monitor/measure_test.go
- simul/monitor/monitor.go
- simul/monitor/monitor_test.go
- simul/monitor/proxy_test.go
- simul/monitor/stats.go
- simul/monitor/stats_test.go
This PR fixes https://github.com/dedis/onet/issues/77
> [Monitor] Stats Locking problem.

- Makefile
- local.go
- treenode.go
Closes https://github.com/dedis/cothority/issues/764
And another bug I saw in Travis...
> merging only relevant changes from debugging_cothority764

- simulation.go
- simulation_test.go
> Merge from v1.0 88

- websocket.go
- websocket_test.go
Closes #86 
Needs fix from #88 to pass checks.
> Same origin 86

- network/network_test.go
- network/router.go
- network/router_test.go
> Sum up Rx/Tx correctly in `network.Router`

- app/libtest.sh
- context.go
- local.go
- simul/manage/count_test.go
> Service load save 102

- simul/manage/count.go
- simul/platform/.gitignore
- simul/platform/cliutils.go
- simul/platform/mininet.go
- simul/platform/mininet/install_mininet.sh
- simul/platform/mininet/setup_iccluster.sh
- simul/platform/mininet/setup_servers.sh
- simul/platform/mininet/start.py
- simul/platform/mininet_test.go
- simul/platform/platform.go
- simul/platform/runsimul.go
> Mininet 85

- app/libtest.sh
> fixed all issues in 110

- websocket.go
- websocket_test.go
> websocket: add Tx / Rx method to websocket client

- simul/build.go
Instead of waiting for the end of `platform.Wait`, wait for the end of `monitor.Listen`.
> waiting for end of monitor

- app/libtest.sh
- simul/build.go
- websocket.go
- websocket_test.go
> V1.0 merge

- simul/platform/mininet/start.py
> Mininet 125

- log/lvl.go
> don't print if not needed

- CHANGELOG.md
- README.md
> added changelog and a reference in the README

- processor.go
> corrected error

- simulation.go
> removed crypto-check

- simul/platform/deterlab.go
- simul/platform/deterlab_test.go
> Deterlab nodes 140

- app/server.go
> added startup-checks

- processor.go
- processor_test.go
> modified definition of service functions

- migration.sh
> added migration script

- tree_test.go
> removed hardcoded tmp directory

- tree.go
- tree_test.go
> replaced Fatal with Lvl2 and added test

- simul/platform/platform.go
- simul/platform/platform_test.go
> fixed toml parsing

- app/server.go
- migration.sh
- processor.go
- processor_test.go
- simul/platform/platform.go
- simul/platform/platform_test.go
- simul/platform/runsimul.go
- tree.go
- tree_test.go
Updating PR - cherry-picking _some_ (not all) from `master`.
> V1 update 170330

- simul/platform/mininet/setup_servers.sh
- simul/platform/mininet/start.py
> debugging done

- context_test.go
> removed hardcoded file name

- context.go
- context_test.go
> adding mutex for testing

- simul/README.md
- simul/build.go
- simul/manage/simulation/everyroundstats.toml
- simul/manage/simulation/individualstats.toml
- simul/manage/simulation/simul_test.go
- simul/monitor/stats.go
- simul/platform/runsimul.go
Closes #171 
Also includes simplification of the simulation-code that has never been used: re-starting failing simulations.
> adding flag to print every round-stat instead of averageing them

- websocket.go
- websocket_test.go
Correct measuring of receiving byes.
> adding correct buffer to receive

- overlay.go
- treenode.go
- treenode_test.go
> passes config to all children

- app/libtest.sh
> Realpath 181

- app/libtest.sh
> Added realpath check  181 (#182)

- log/lvl.go
With regard to the bug in
https://travis-ci.org/dedis/onet/builds/242306551?utm_source=github_status&utm_medium=notification
> added correct locking

- protocol.go
lvl1 - test-messages and important messages from apps
lvl2 - important messages from services
lvl3 - messages that might help debug
lvl4 - debugging only in special cases
lvl5 - spamming debug-lvl and huge messages
> changed log-lvl to 3

- simul/platform/platform.go
closes #124 
the first issue "`setup_iccluster.sh` doesn't find `install_mininet.sh`" was resolved in #164
> ask for servers

- Makefile
- simul/manage/close_all_test.go
- simul/monitor/monitor.go
> moved locking

- websocket.go
- websocket_test.go
> corrected bug

- network/address.go
- network/address_test.go
Added few (temporary) tests
It has to be integrated with the rest
> Added validHostname as isolated function.

- network/address.go
- network/address_test.go
> handle local ipv6 addresses

- simul/build.go
- simul/build_test.go
> fixed division by zero error

- app/server.go
> Portscan 212

- app/server.go
> Portscan 212 - to backport on master (#213)

- simul/platform/platform.go
if `server_list` exists, use that.
> check on existing server_list

- simul/platform/platform.go
> porting to v1

- simul/platform/mininet/install_mininet.sh
- simul/platform/mininet/setup_servers.sh
- simul/platform/mininet/start.py
Makes installation on ubuntu 1604 possible
> V1 mininet 1604

- simul/platform/mininet/install_mininet.sh
- simul/platform/mininet/setup_servers.sh
- simul/platform/mininet/start.py
* using standard ubuntu-packages
* adding psmisc and automatically install packets
* tested on fresh 1404 and 1604
> mininet 1604

- node_test.go
- treenode.go
- treenode_test.go
> fail if receiving-channel is full

- network/tcp.go
- network/tcp_test.go
* Add check of the packet size
Closes #189
> Add input validation

- app/libtest.sh
- crypto/key.go
small clean-ups from stable movement.
> Cleaning up

- treenode.go
> correct testing of equality

- service_test.go
- treenode.go
> testing that a new protocol is correctly tied to a service

- tree.go
- tree_test.go
> Tree generation without rewriting the roster

- .travis.yml
- simul/test_simul/count.toml
- simul/test_simul/show_date.sh
- simul/test_simul/simul.go
- simul/test_simul/simul_test.go
- tree.go
- tree_test.go
> merging from master

- tree.go
- tree_test.go
Now that master is in `unstable` mode, we need to cherry-pick...
> added OnCurrent method and tests

- app/libtest.sh
Small omission when cleaning up
> fix libtest.sh to use kyber/suites

- app/config.go
- app/config_test.go
- app/server.go
- messages.go
- network/struct.go
- network/struct_test.go
- onet.go
> Do not use base64 in toml files anymore.

- context.go
Please also review the database wiki page https://github.com/dedis/onet/wiki/Database-backup-and-recovery
> Improve database docs

- network/dispatch.go
If the processor for the message wants to call back into
the dispatcher for something, it will double lock, and deadlock.
Release the lock after the map read is done.
Closes #277
> Unlock dispatcher before processing message

- simul/build.go
- simul/manage/simulation/count.toml
- simul/manage/simulation/csv1.toml
- simul/manage/simulation/csv2.toml
- simul/manage/simulation/individualstats.toml
- simul/platform/deterlab.go
- simul/platform/localhost.go
- simul/platform/mininet/start.py
- simul/platform/runsimul.go
- simul/simul.go
- simulation.go
- simulation_test.go
The `users`-binary in deterlab didn't get the suite. Trying to propagate it correctly.
Also includes a fix for mininet-script: clean up all servers, and only then start the simulation.
> adding suite argument to deterlab

- .travis.yml
- network/tcp.go
- treenode.go
> Remove calls to log.Stack that are no longer needed

- app/libtest.sh
- overlay.go
- treenode.go
- making libtest.sh silent when needed
- formatting it with 2 spaces instead of tab
- changed wrong format in print
> libtest.sh changes

- simul/README.md
- simul/build.go
- simul/manage/count.go
- simul/manage/count_test.go
- simul/platform/platform.go
- simul/platform/platform_test.go
- simul/platform/runsimul.go
> Change timeout integers to time.Duration

- local_test.go
- processor.go
- processor_test.go
- service.go
- service_test.go
- websocket.go
- websocket_test.go
> Remove onet.ClientError

- app/libtest.sh
- service.go
Replacing `127.0.0.1` with `localhost` in libtest.sh
> using localhost in libtest.sh

- app/server.go
- app/server_test.go
- local.go
- local_test.go
- overlay.go
- processor_test.go
- protocol.go
- server.go
- server_test.go
- service_test.go
- status_test.go
- websocket.go
- websocket_test.go
> Suite as the first argument

- simul/build.go
- simul/platform/deterlab.go
- simul/platform/mininet.go
- simul/platform/platform.go
Also: Fix the type of RunWait for deterlab.
Fixes #323.
> Make it easier to debug when RunWait is set wrong

- local.go
I couple more that I missed in https://github.com/dedis/onet/pull/322
> Move suite to first argument

- simul/platform/cliutils.go
- simul/platform/platform_test.go
> Speed up building by installing the cross-compilation libs

- context.go
- local.go
Also: Remove an unused field
Fixes #230.
> Remove unused context.Dispatcher

- local.go
- overlay.go
- server.go
> Add an expiration mechanism to the TreeNodeCache

- tree.go
- tree_test.go
> breaking API

- processor.go
- processor_test.go
- websocket.go
- websocket_test.go
Helping students find their errors...
> Improve websocket errors

- server.go
- websocket.go
> more logging for startup

- websocket.go
Output if a websocket-call returns an error.
> if websocket call fails, print Lvl3 error

- log/lvl.go
- log/lvl_test.go
With the current behaviour of `MainTestWait`, the `timeout` flag is ignored if the test uses `log.MainTest`. This deprecates the use of `MainTestWait` (it is still working) and includes a fix to honour the `timeout` flag if it is set.
> dont use MainTestWait anymore

- local.go
- node_test.go
- server.go
- treenode.go
> Help testing byzgen

- server.go
Correctly log what the server is doing before blocking.
> log before calling websockets

- simul/platform/localhost.go
- simul/platform/mininet.go
- Changed 'ErrFatal' to returning the error whenever possible in 'simul/platform'.
- Fixed 'Cleanup' in 'mininet.go'.
Fixes #366
> Cleaned 'simul/platform' and fix bug in Cleanup of mininet

- treenode.go
Removes a race when sending to a channel in a closed protocolInstance.
> removing race in closing channel

- app/config_test.go
- local.go
- log/lvl.go
- log/lvl_test.go
- network/big_test.go
- network/local_test.go
- network/struct.go
- network/tcp.go
- network/tcp_test.go
- node_test.go
- overlay.go
- protocol.go
- server.go
- simul/platform/localhost.go
- simul/platform/mininet.go
- simulation.go
- simulation_test.go
- tree_test.go
- treenode.go
Merging of latest changes into `v2`.
> create stable of latest master

- app/config.go
> Set the permissions correctly on private.toml

- simul/README.md
Adding description of mininet variables.
> adding mininet variables

- network/router.go
- network/router_test.go
`Router.Send` is now checking if we are sending a message to ourselves, and if this is the case, it will directly dispatch the message without opening a connection with ourselves.
> Router should not open a connection when sending message to itself.

- network/router.go
- server.go
- websocket.go
There were only some logging messages that weren't merged yet.
> Merge byzgen poc

- local.go
This can be used at the end of tests to wait for protocols to finish.
By default, `local.CloseAll` waits for 1 second for them to finish.
If a test needs a longer wait, he can do so before calling `local.CloseAll()`.
> Adding WaitDone

- app/libtest.sh
> Waiting for one second when testing with conodes

- local.go
Making the report nicer and tell you why it failed with more details.
> report which protocols or servers have lingering stuff inside

- README.md
Forgot to add navigation bar to README.md
> Add Navigation

- simul/platform/deterlab.go
> adding tags to deterlab

- simul/build.go
> globals are bad

- log/lvl.go
> fixed line-# padding

- simul/platform/deterlab.go
- simul/platform/localhost.go
- simul/platform/mininet.go
if no runwait is given, there should be no error message
> Fix RunWait parsing

- simul/platform/runsimul.go
Changed 'return err' to 'return errors.New('explanation: ' + err.Error())'
> better report errors in the simulation

- tree.go
- tree_test.go
Needed for https://github.com/dedis/cothority/issues/1362
> Add a function to check roster rotation

- log/ui.go
- log/ui_test.go
- service.go
- simul/monitor/stats.go
- simul/platform/platform.go
- simul/platform/platform_test.go
- simul/test_simul/count.toml
- simul/test_simul/simul.go
Fixes #446.
Also: Fix the incorrect fix to log.Panic I recently made.
> Simulation files can contain strings that vary across runs

- README.md
- app/README.md
- app/libtest.sh
For better understanding how to use libtest.sh, here is a documentation
pointing out the structure and the test-methods available to be
used.
> Adding libtest-documentation

- app/README.md
- app/libtest.sh
- context.go
- context_test.go
- log/syslog.go
- log/ui.go
- log/ui_test.go
- network/router.go
- server.go
- service.go
- simul/build.go
- simul/manage/count.go
- simul/monitor/stats.go
- simul/platform/deterlab.go
- simul/platform/fd_unix.go
- simul/platform/fd_windows.go
- simul/platform/localhost.go
- simul/platform/mininet.go
- simul/platform/mininet/start.py
- simul/platform/platform.go
- simul/platform/platform_test.go
- simul/test_simul/count.toml
- simul/test_simul/count_big.toml
- simul/test_simul/simul.go
- simulation.go
> updating to latest changes from master

- app/server.go
https://dedis.ch/portscan.php does not seem to work so changed to 3rd public one https://api.ipify.org?format=text
> change non-working public ip detetcion service to 3rd party working one

- server.go
- service.go
`serviceManager.services` needed a mutex.
> Putting a mutex on the service-slice in serviceManager

- node_test.go
- treenode.go
Don't allow sending if the service is closing down.
> handling closing of service

- overlay.go
This moves the transmission of pending messages
out of the lock scope so that it is freed after
extracting the messages.
Fixes #482
> Pending messages in overlay

- tree.go
There was a possible panic in case the roster was not correct. But malicious nodes
might send bad rosters, so this should not panic.
> Checking TreeMarshal

- tree.go
We noticed that calls to rand.Perm were always returning
in the same permutations during testing. This was because
callers to onet had no idea they needed to call rand.Seed
to seed the global random number generator. As this library
is targeted at security-critical use cases, take the conservative
option and use cryptographically secure seeding for rand.Perm.
Fixes dedis/cothority#1587.
> Securely seed rand.Perm

- context.go
- local_test.go
- network/dispatch.go
- network/dispatch_test.go
- network/tls_test.go
- service.go
- service_test.go
- simul/platform/runsimul.go
> Change the signature to allow the callback to log an error

- simul/build.go
- simul/build_test.go
> Clarify CheckHosts and improve testing

- network/router.go
- network/router_test.go
- simul/monitor/measure.go
- simul/monitor/measure_test.go
This adds a message/packet counter alongside with the bytes counter
> Simulation: add a message counter in the measures

- app/config.go
ParseCothority should really have been called "load
cothority config and make a server", which is not really
what external callers who just want to load the private
key need.
> Refactor to make LoadCothority available to external callers

- .gitignore
- go.mod
- simul/platform/deterlab.go
- simul/platform/fd_darwin.go
- simul/platform/platform.go
Also: Improve some error reporting.
> Apply Go 1.12/Darwin file descriptor fix

- app/server.go
The default timeout was way too long and no message was displayed telling the user what was happening.
Fixes #540
> Adds a timeout of 10 sec when checking the public address

- simul/platform/runsimul.go
This changes the simulation to only records the bandwidth of the servers
right before the simulation actually run to prevent messages not related
with the simulation to be taken in account.
> Simulation: record bandwidth only before and after the simulation run

- processor.go
- processor_test.go
I noticed we weren't using JSON errors as described here https://developer.github.com/v3/#client-errors. This PR fixes this issue.
> Use JSON errors

- websocket.go
Here is where I lost my love for go-channels (that was never too strong):
- `select` read on a closed go-channel will return values, as long as there are values
- `select` on a closed go-channel and a channel with values will return either one, depending on the stars
> Correctly stop sending messages

- websocket.go
- websocket_test.go
The all-error path was wrong and not correctly handled. Also update the test to check if it behaves correctly now.
> All error path

- simul/build.go
- simul/platform/localhost.go
- simul/platform/runsimul.go
> Clean up simulation before returning errors

- websocket.go
To avoid too many requests on nodes, decode the correct replies already in the
go-routine. This avoids the channel filling up with potential correct
data that will only be checked in the consumer-loop.
This also simplifies the number of channels used.
Replaces #570
> Check decoding in go-routine

- app/config.go
- app/config_test.go
- websocket.go
- websocket_test.go
> Reload ssl certificate

- protocol.go
> Fix comment (DispatchMsg → ProcessProtocolMsg)

- tracing/logger.go
- tracing/trace.go
- tracing/trace_test.go
Even after hours of testing, this one came up 10 seconds after Jeff merged :(
> Don't unfold arrays in fields sent to the tracing-service

- simul/platform/mininet.go
- simul/platform/platform.go
Closes #631
Moved all initialization of mininet to mininet.go.
Now correctly searches the path for all scripts that should be run.
> Fixes issue with simulation

- processor.go
- treestorage_test.go
This fixes the issues found by gofmt -s to comply to dedis/Coding#4.
> Fix gofmt advice

- network/dispatch.go
- tracing/logger.go
- treenode.go
Reduce the amount of tracing that is sent to honeycomb,
as currently there are peaks that are not recorded.
After this PR is accepted, could you please also bump the onet version?
OR review - first one to agree, please merge ;)
> Set log-level to 3 for tracing

- context.go
- network/router.go
See commit messages.
Closes c4dt/TODO#143
> Filter in out connections

- simul/build.go
- simul/platform/cliutils.go
- simul/platform/deterlab.go
These are minor changes I made while I was looking into failures on DETERLab yesterday.
> Minor fixes found while debugging

- context.go
- go.mod
- go.sum
- messages.go
- network/encoding.go
- network/encoding_test.go
- network/struct.go
- node_test.go
- overlay.go
- overlay_test.go
- protocol.go
- protocol_test.go
- server_test.go
- service.go
- tree.go
- websocket_test.go
Replaces gopkg.in urfave/cli and satori/uuid with their go-modules.
Closes #591
> Replace gopkg.in with go-mod

- go.mod
- go.sum
- log/testutil.go
- websocket.go
> Remove dependency on tylerb/graceful

- .travis.yml
- log/syslog.go
- network/big_test.go
- network/local_test.go
- network/router_test.go
- node_test.go
- protocol_test.go
- simul/monitor/rtime.go
- simul/monitor/rtime_windows.go
- simul/platform/fd_unix.go
- simul/platform/fd_windows.go
Updates the tests so that they pass with go 1.17.
> Test with go 1.17.x
