network/encoding.go
network/encoding_test.go
network/tcp.go

In encoding.go when it receives an unknown type, it calls `type.Name()` while the `type` is nil, because we wanted nice error output :(

[Network] Fixing panic memory invalid address

---

Makefile

Currently, the command from goveralls does not make race detection checks. This PR aims to fix that by adding `-race` and `-covermode=atomic` to the testing command.

[Travis] Goveralls with race detection enabled

---

messages.go
overlay.go
service.go
service_test.go
treenode.go

This PR fixes #30 . Namely, it adds the possibility of giving a generic config by calling `treenodeinstance.SetConfig` by creating a new protocol. The config will be available in the `NewProtocol` of the corresponding `Service`.

[Onet] Generic Config implementation

---

websocket.go
websocket_test.go

closes #35 
Added correct header to `Client.Send` to respect same-origin policy.

respecting same-origin policy

---

context.go
local.go
node_test.go
onet.go
overlay.go
overlay_test.go
processor.go
server.go
service.go
service_test.go
simulation.go
treenode.go

This PR is a first shot to reducing the exported API that we have in Onet and which is not used at all elsewhere, and which should not be used at all elsewhere.
If a method has been privatized, it's because it's building everywhere, including cothority (i.e. cothority does not use it).
**Note**: One last thing I'd like to reduce is the `CloseHost` method on `TreeNodeInstance` which basically shutdowns everything... It's bad ! Unfortunatly it's used in the simulation,which is in a diferent package. Any ideas ?

[Onet] Reducing unused exported API

---

websocket.go

This PR fixes #17 : it makes possible to have a clean shutdown of a conode's websocket server while being to stop it correctly for the tests.

[Websocket] Graceful shutdown working

---

network/router.go
network/router_test.go

Gives the service the opportunity to register a error-handler function (type `func(*ServerIdentity)`). This function will be called on network error: Timeout, EOF, or ConnectionClosed, with the identity of the faulty remote server.

Adds ErrorHandler accessors

---

app/config.go
app/config_test.go

Makes app.Group's Description field public. There is no constructor, and I need to set the description file for the simulations.

Makes app.Group's Description field public

---

app/config.go
app/server.go
context_test.go
crypto/hash.go
crypto/hash_test.go
crypto/key.go
crypto/key_test.go
crypto/schnorr.go
crypto/schnorr_test.go
local.go
network/encoding.go
network/struct.go
network/struct_test.go
network/tcp_test.go
overlay.go
server.go
simulation.go
tree.go
tree_test.go
treenode.go

This PR fixes #106 : it moves all dependencies from `github.com/dedis/crypto` to `gopkg.in/dedis/crypto.v0`.

[Crypto] Moving to v0

---

crypto/key.go
crypto/key_test.go

Now we have all of
`(Read|Write)(64|Hex)(Scalar|Pub)`
and
`String(64|Hex)To(Scalar|Pub)`
and
`(Scalar|Pub)ToString(64|Hex)`
For V2: replace `Pub` with `Point`, see #116

adding all missing functions

---

simul/simul.go

When calling `simul.Start`, the directory will be changed. So we cannot call it multiple times :(

change directory in a consistent way

---

app/config.go
app/server.go
crypto/key.go
crypto/key_test.go
network/struct.go

A lot of these functions contains a abstract.Suite as first argument, which is unused. Why is so?
Solved #116

Rename every 'Public' in abstract 'Point' instead

---

simul/platform/runsimul.go

In simulation-mode, this adds a listener to all servers, so that it can receive a broadcast-message and then start the `simulation.Node`. This makes sure that all nodes are up before `simulation.Node` is called.

starting simulation.Node only once all conodes are started

---

overlay.go

This PR is a quick fix to remove the annoying log.Error output from overlay message.

Log.Error to log.Lvl5 for late message to overlay

---

crypto/hash_test.go
local.go
messages.go
network/big_test.go
network/encoding.go
network/encoding_test.go
network/struct.go
node_test.go
overlay.go
overlay_test.go
processor_test.go
protocol.go
protocol_test.go
service.go
service_test.go
simul/platform/runsimul.go
simulation_test.go
tree.go
tree_test.go
treenode.go
treenode_test.go

Merging things from master back into v1.0
One question: are the changes to the IDs too much of an API-change? There is one incompatible change: `Tree.Equals` got changed to `Tree.Equal`.
- change it back to `Tree.Equals`?
- prepare it for v1.1/v2.0?

V1.0 merge

---

messages.proto
network/network.proto

`protoc` in its later versions complains if there is no `proto2`.

added proto2-definition

---

server.go
server_test.go

`Server` and `Context` both have a method to retrieve a given service. Unfortunately they are not called the same, so this patch unifies the naming, while keeping backwards-compatibility (`prifi` uses the `Server.GetService`) and printing out a warning that `Server.GetService` is deprecated.

unifying Server and Context with regard to Service-method

---

websocket.go

worst thing is that I knew about this one. For `v2` I really need to kill `ClientError` - what a bad idea...

dont cut off string after second :

---

app/libtest.sh

Instead of using a constant temp-file, use `mktemp`.

compatibility for mac and more than one user

---

network/tcp.go
network/tcp_test.go

If you need bigger packets, you should be able to increase the size.
Rant: if we would have put a hash or some magic bytes we wouldn't need this ;)

exporting MaxPacketSize

---

crypto/schnorr.go

The onet-schnorr-signature is a not-eddsa-compatible schnorr signature. For v2 we'll have to remove it. For previous versions, I propose we change the hash to the below function, so that the javascript-implementation from the epfl e-voting project can easily interact with the cothority.

changing the way the hash is calculated

---

overlay.go
overlay_test.go

Fixes #237 
The `TestOverlayDispatchFailure` test passes with `go test -v .`, but fails when using `go test .`. This issue is most likely due to how `go test` changes the stderr, needs further investigation.

Attempt to add dispatch failure message

---

app/libtest.sh

While porting, `libtest.sh` wasn't tested. This adds a standard ed25519 suite for the apps. Of course this will change once we have a more configurable service/protocol structure.

Added a standard ed25519 as the suite for apps

---

app/libtest.sh

One liner to remove the storage directory between each integration test.

remove service_storage directory after each test

---

context.go
context_test.go

Instead of returning the existing bucket, change the method to create a new bucket, if it doesn't exist yet. It also makes sure that the names are conode-unique by prepending the name of the service to the request.

adding new function to context to create a new bucket

---

local.go
network/local.go
network/local_test.go
network/router.go
tree.go
tree_test.go

RandomSubset is used to choose some of the nodes in a roster
to contact. It is used when we want at least one answer from a set
of conodes, but we don't care which one we contact, and we want
to tolerate some of the nodes being down.
GenerateStar makes a star-shaped tree, which causes the root to
send the request to all children.
Closing local tests is now more reliable with respect to leaving
goroutines running.

Add roster.RandomSubset

---

treenode.go

I wanted to do this a long time already. Now we have all four:
- `RegisterChannel`
- `RegisterChannels`
- `RegisterChannelLength`
- `RegisterChannelsLength`

adding RegisterChannelsLength convenience method

---

network/address.go
network/address_test.go
network/tcp.go

While testing, people sometimes want to use non-fully qualified domain names. Allow those, too.

Allow non fqdn

---

local.go
network/local.go
network/local_test.go

The `LocalTest.Stop` function was misbehaving in that it supposed all connections were closed before it got called, which is not always the case.
This PR also changes the way `local.CloseAll` behaves: if `go test` is called without `-v`, `local.CloseAll` reroutes all logging to `/dev/null` while closing, as there might be quite some error messages due to late packets arriving.

fixing a bug in LocalTest cleanup

---

processor.go
processor_test.go
websocket.go

Relax constraint on return value to be ClientError. If it is
not a ClientError, then convert it for now.

First step to removing ClientError

---

simul/platform/runsimul.go

In some situations the tree from the simulation is not a good tree to use for `CloseAll`. So always do the rearranging of the tree in binary form, as this seems to work the best.

always rearrange tree in simulation

---

local.go

If list is nil, and we try to dereference it by doing list.ID, the code
panics. Instead, we should return a nil roster to the caller.

Handle nil return value

---

network/router_test.go
network/struct.go
network/tcp.go

Count all the bytes, and also count them if there's an error.
Also: defer costs a memory allocation, don't use them when not needed.
Fixes #292.

Count bytes more correctly

---

context.go
network/struct.go
processor.go
server.go
service.go
status.go
status_test.go

Simplify the type for the status replies. Add DB stats.
Make it possible for non-Onet packages to register
status methods.
Also: Make NewServerIdentity tolerate not having the public
key, which is needed for how scmgr calls it.
Updates dedis/cothority#940.

Status cleanup and DB status addition

---

log/lvl.go
log/lvl_test.go
log/ui_test.go
network/router.go
node_test.go
simul/platform/localhost.go
websocket.go

Tune logging so that auditing and errors go out at level 2.
Also: Add an HTTP responder for "/ok" so that HTTP load balancers can detect if a conode is alive.

Tune logging for production use

---

network/router_test.go
treenode.go

Code of the form "if len(chan)==0 { send }" is racy because two
goroutines could observe len == 0, and then both try to send. One
will block when it expected to not do so. Replace with a select
to correctly implement the desired behavior that the two goroutines
end up not blocked, and the channel ends up with one value on it.
We have not seen any indication this is causing a bug, but
leaving racy code around is asking for trouble.
Also: Make a flaky test stop failing, since the thing it is
checking is not very important. When this test runs against the
"local" router, it never fails, indicating that this is
a benign race in the TCP implementation, not in our Router.
Fixes #305.

Remove race condition in message dispatcher

---

network/struct.go
processor.go
processor_test.go
service.go
service_test.go
websocket.go
websocket_test.go

So that it can make decisions based on who the
remote client is, or what the state of TLS is, etc.
Fixes #331.

Give ProcessClientRequest the HTTP Request

---

simul/platform/runsimul.go

Otherwise `pi` might be nil and the code panics.

Check protocol error before starting it

---

app/server.go

It is checking something that is not so critical
now that runaway memory allocation is solved, and
it results in three extra package dependencies that
we don't really want.
Fixes #346.

Remove checkAvailableMemory

---

context.go
context_test.go

Use `[]byte` for `bucketName` to avoid alocation and use `[]byte` in the DB wrapper functions such as Load/Save.
This change breaks cothority, so we'd want to merge https://github.com/dedis/cothority/pull/1090 quickly after this one

Use []byte for bucketName/Load/Save

---

context.go
network/big_test.go
network/local.go
network/local_test.go
network/network.go
network/router.go
network/router_test.go
network/tcp.go
network/tcp_test.go
network/tls_test.go
overlay.go
overlay_test.go
service_test.go
simul/monitor/measure.go
treenode.go
treenode_test.go

This PR changes the `Conn` interface where `Send() error` is now `Send (uint64, error)`, and adds the CounterIO interface to TreeNodeInstance and Overlay.
It makes https://github.com/dedis/onet/pull/265 and https://github.com/dedis/onet/pull/264 redundant as it should be an accurate way to count tx/rx. However, I did not add a CounterIO interface to Context because there wasn't an obvious way to do it and Crux only needs it on TreeNodeInstance. Further, since Crux is a long-term project and should be eventually be ported to onet.v2, I do not plan to backport this change to onet.v1.

Add CounterIO interface to TreeNodeInstance and Overlay

---

local.go
overlay.go
server.go
tree.go
tree_test.go

@kc1212 and @ineiti found that trees and rosters were very badly set up:
- every time `NewRosterWithRoot` is called, the roster gets a new, random ID
- every time `GenerateNaryTreeWithRoot` is called, even for the same tree, it gets a random ID
-> every call for a new skipchain-block will create a new roster/tree - and they are not cleaned up!
Now we changed it so that rosters depend on the order of the ServerIdentities, and trees depend on the roster and the order of the nodes in the tree. But no random IDs anymore.

First try at removing some overlay memory leaks.

---

simul/platform/mininet.go
simul/platform/mininet_test.go

This fix should allow the user to decide the number of servers she/he wants to use by putting the corresponding number in the 'Servers' field in the .toml file. Even if there are more servers than that in the 'server_list' file, it will only take the first 'Servers' ones.
One thing I'm not 100% sure is if we should change the Cleanup() function in mininet.go. Maybe the way it's done now can make the last cleanup(s) fail..?
Fixes #175

Take max Servers from 'server_list' file for mininet

---

network/router.go

If a load balancer connects to our conode-to-conode communication, it will close the connection without sending anything. So ignore EOF errors in the server identity verification.

ignoring EOF in new connections

---

log/lvl.go
log/lvl_test.go
log/ui_test.go

Logging: align method-names and description always, but only adjust the alignment when in color-mode.

allow log-padding even without colors

---

local.go
node_test.go
treenode.go

- `TreeNodeInstance.Info()`: print protocol name
- `LocalTest`: allow list of all `TreeNodeInstances` in tests

Improve testing

---

treenode.go

- Removed what seems to be a useless call to `TreeNodeInstance.closeDispatch()` inside `TreeNodeInstance.Done()`, since it's already called (on the same instance) when calling `Instance.nodeDone()` inside the same function.

Removed double call to 'Shutdown()' inside 'TreeNodeInstance.Done()'

---

app/config_test.go
local.go
network/big_test.go
network/local_test.go
network/tcp.go
network/tcp_test.go
simulation.go
simulation_test.go
tree_test.go

- Created `NewTCPAddress` function in `network/tcp.go`.
- Changed a maximum of TCP `Address` creation with this new function.
- By default, using `PlainTCP` addresses in simulations, instead of `TLS`.
- Added a `TLS` flag `SimulationConfig`, `SimulationConfigFile` and `SimulationBFTree` structures to let the user decide if `TLS` should be used instead of the default `PlainTCP`.
It seems to me that it is necessary to add the `TLS` flag to those 3 structures, maybe it's good if you check that this is indeed the case.
Also, the current tests in `simulation_test.go` can all be run using `PlainTCP`, right?

Simulations using TCP by default, with flag for TLS

---

network/struct.go
overlay.go
treenode.go

When `TransmitMsg` returns error, there is a code execution pass where this error is ignored. Added an error output in that case.
In `TreeNodeInstance.dispatchChannel` there is a rare occasion of a write to a closed channel. Added a `recover` to further debug it.

show errors in message processing

---

local.go
protocol.go
protocol_test.go
server.go

By using a flag to `protocolStorage`, we can now check that no server has already been started while calling `GlobalProtocolRegister`, and if this is the case we `log.Fatal`.
Didn't add a test for this change. Should we? If yes, how to test it cleanly since we use `log.Fatal`?

Fatal when calling GlobalProtocolRegister with server(s) already started

---

overlay.go

Description in the title.
No big investigation was made (like @jeffallen was saying in the connected issue), just a quick replacement of a potential `log.Panic` into an `log.Error`.
Fixes #361

Changed Panic into Error if invalid config packet received in Overlay.

---

cfgpath/cfgpath.go

Because in some Docker containers, user lookups don't work
but $HOME is set just fine.

Prefer $HOME to doing user lookups

---

network/struct.go
network/struct_test.go
network/tcp.go

GlobalBind was not parsing IP addresses correctly. Now it is.
Also check the error it returns in the caller.
This makes it possible for conodes to listen on IPv6 as
well as IPv4.
Fixes #390.

Correct GlobalBind to parse IPv6 correctly

---

context_test.go
onet_test.go
service.go

We do this because, depending on the suites, public keys may be very
long, too long for filesystems. This commit uses the sha256 of the
public key as the database file name and automatically converts old
filenames to the new one.
This feature is a bit difficult to test by unit tests. We have integration
test in cothority/conode. 
Fixes #399

Use sha256(pk) as the database name

---

server.go
service.go
service_test.go
websocket.go

Catch panics coming from services so that one service cannot
crash the whole server.
Fixes #409.

Do not let a panic is NewProtocol take down entire server

---

app/config.go
app/config_test.go
local.go
server.go
service.go
status_test.go
websocket.go
websocket_test.go

- Added 2 fields in `private.toml` for setting the WebSocket TLS certificate and key, if wanted.
- `WebSocket` is now using `ListenAndServeTLS` using the TLS configuration found in the `private.toml` if given.
- `Client` (in `websocket.go`) can now communicate in TLS, if asked.
In the `private.toml` file, we can set the 2 WebSocket TLS fields using 2 different ways:
- `string://{THE CONTENT OF THE CERTIFICATE}`
- `file://{THE PATH OF THE FILE CONTAINING THE CERTIFICATE}`
Fixes #383

Added TLS to WebSocket

---

log/lvl_test.go
processor_test.go
websocket_test.go

Make log-tests pass also with new coveralls.sh that uses `DEBUG_TIME=true`

pass tests with DEBUG_TIME=true

---

simul/platform/localhost.go

Because simul/build.go has a global holding the test and uses it in different
simulations, we need to hold a mutex, at least for localhost.

adding mutex to Localhost

---

stable/script

This script is used in `create_stable.sh`, but it's out of date. We update it.

Update stable script

---

network/router.go

Comparing addresses can lead to issues due to canonicalisation. Comparing `ServerIdentity`'s ID to know if we are sending a message to ourself is thus better.
Fixes #423

Comparing ServerIdentityID when checking if sending package to ourself.

---

Makefile
local.go
local_test.go
log/testutil.go
network/dispatch.go
network/router_test.go
node_test.go
overlay.go
overlay_test.go
protocol_test.go
server.go
service_test.go
simul/monitor/tcpproxy.go
simulation_test.go
status_test.go
treenode.go
treenode_test.go
websocket.go
websocket_test.go

During tests, a service might still have 'Process'es running,
when working on messages sent with 'SendRaw'.
This PR allows the 'Local' test to wait for these running
processes and put an error if they take too long.
Also adjusted all tests in onet to work correctly with the
new local-test cleanup verification.
It will break cothority, because some of Cothority's tests
are not correct...
**Please review but don't merge before cothority-patch-PR is not merged**

Waiting on processes

---

local.go
server.go
simulation_test.go
status_test.go
websocket.go
websocket_test.go

server.Start is again blocking, so as not to break existing software.
There are two new methods:
- server.StartReturn calls server.Start in a goroutine and waits for all ports to be listening
- server.WaitStartup loops until the server is completely started up

unbreaking server.Start behaviour

---

local.go
log/testutil.go
stable/script

This PR allows for three levels of checks:
- 0: no leaky test at all
- 1: only log.AfterTest
- 2: like 1 and test for leaky processors or protocolInstances (default)

Allow different levels of CloseAll checks

---

simul/platform/deterlab.go
simul/platform/localhost.go
simul/platform/mininet.go

Different platforms had different implementations on what to do with `RunWait`. Unified it.

parsing RunWait in localhost, mininet and deterlab

---

simul/README.md

Fixes #444 
Adding two more examples to the documentation, illustrating how to set delays in MiniNet.

Mininet documentation example

---

local.go
local_test.go

I had several instances where the code was panicking, but `defer CloseAll()` overwrote the panic with a `Fatal` about still existing go-routines.
This puts panic at a higher priority than leaking go-routines.

correctly panicking when CloseAll is called from defer

---

log/loggers.go
log/syslog.go

Windows does not have syslog, so we need to use build tags to fix the
build.
Fixes dedis/cothority#1326.

Move syslog into Unix-only source code

---

local.go
local_test.go
log/lvl.go

Allows for easier setup of `LocalTest` for inclusion of `testing.T`, so that `CloseAll` will not verify running go-routines if a test fails.
Also added a test in `log.MainTest` to make sure that no running go routines are tested if the return-code is != 0. This should make the tests even better!

Don't search for missing go-routines in CloseAll if a test fails

---

local.go
local_test.go
server.go
simul/platform/runsimul.go

If a service implements a `TestClose` method, it will be called in `LocalTest.CloseAll()`.

Adding a TestClose interface

---

simul/platform/platform.go

For simulation.toml files, all # are now ignored everywhere

ignore # in .toml

---

simul/platform/deterlab.go
simul/platform/localhost.go
simul/platform/mininet.go

If we can't parse RunWait, the code will automatically pick a default
value. Hence, there is no reason to return and propagate the error up
the stack.

Do not return error when we use default RunWait

---

network/router.go
server.go
simul/build.go
simul/manage/count.go
simul/platform/deterlab.go
simul/platform/fd_unix.go
simul/platform/fd_windows.go
simul/platform/localhost.go
simul/platform/mininet.go
simul/platform/mininet/start.py
simul/test_simul/count_big.toml
simulation.go

Changes the start.py script to set up ip2ip tunnels between all hosts,
so that it also works when the iccluster-servers are on different
subnets.
In addition, there are some small cleanups and specifically the setting
of the maximum numbers of file descriptors that makes bigger simulations
passing on MacOSX.

Adding ip2ip tunnel and cleaning up

---

context.go
context_test.go
service.go

This PR adds LoadVersion and SaveVersion to store a db-version int for every service.
It also adds LoadRaw to fetch old versions of the db.

Add versions to db

---

local.go
overlay.go
server_test.go

Makes a nicer closing of tests by asking the services _first_ to shut down,
and only then closing the network.

Test Closing Fixes

---

server.go
service.go

Instead of filling up the local protocol stack with the list of global protocols
_after_ service creation, do so before. This allows services to actually use the
protocols in their 'newService' method.

Fixing protocol creation

---

local.go
server.go

We run TestClose in parallel because if one of the TestClose takes a
long time then it may cause strange behaviour in other services.

Run TestClose in parallel

---

log/log.go
log/nonblock_unix.go
log/nonblock_windows.go
overlay_test.go

By adding in non-blocking logging and a fix for a recently destabilised test.

Improve test robustness some more

---

network/tcp.go
network/tcp_test.go
network/tls.go

There was an existing timeout for reads. Rename it and then use it to prevent
sends from taking too long, with/without the need to connect.
Fixes #468.

Apply the same timeout for reads to send and connect too

---

local.go
server.go
service.go

Parallelizes the closing of the servers so that the nodes don't wait for each other.
Unlocks the servicesMutex before waiting for all servers to finish.

Improving shutdown of tests

---

local.go
processor.go
processor_test.go
service.go
service_test.go
websocket.go
websocket_test.go

Adding streaming abilities to onet websockets.
We introduce a way to register handlers - `RegisterStreamingHandler`. This handler will return a channel to stream data to the client upon receiving a message. Internally, the processor listens on the channel and forwards all the messages to the websocket loop which then forwards them to the client.
If the client closes its connection. The websocket loop sends a stop signal back up the path to tell the service to stop streaming.
There shouldn't be any backward incompatible changes, `make test` works on cothority master.

Adding streaming abilities to onet websockets

---

.gitignore
app/config.go
app/config_test.go
local.go
network/struct.go
simul/monitor/tcpproxy.go
websocket.go
websocket_test.go

This change makes it possible to indicate to the websocket
client where it should contact a given server. In the past, the
websocket side of all servers had to be on port p+1. With
this change, it is possible to indicate in a roster.toml
file the correct URL to use to contact a given server.
Also: Fixed a problem go vet found.

Optionally list the WebSocket-side URL in ServerIdentity

---

tree.go
tree_test.go

This PR adds a Contains function to the Roster struct that will check if the given list of public keys is the same list (but in a different order) as for the Roster.
Requirement for the issue cothority-1538

Public keys comparison for a roster

---

cache.go
cache_test.go
overlay.go
server.go

This PR changes the cache to use a LRU policy with a maximum number of entries. This maximum is for the moment static when instantiating the cache.
It also removes the goroutine that cleans the expired items by a simple check when getting elements as we can simply check the tail expiration.
Fixes #273

LRU cache with maximum size onet-273

---

local.go
local_test.go

For a new test with new nodes it is easier to create a first set of nodes, then
add the second set of nodes later.

Adding servers later

---

service.go

The panic was too noisy, fatal lets the user more easily find and read the error message.
This is needed to make the ByzCoin database version message more visible.

Do not panic on failure to start a service.

---

messages.go
network/local.go
network/struct.go
network/tcp.go
overlay.go
treenode.go
treenode_test.go

This fixes the rx status that was always 0 even
after processing a message.
Fixes #481

Fix TreeNodeInstance rx status

---

tree.go
tree_test.go

This adds a function that will create a new roster using an existing
one and a list of server identities.
The helper function will be use to concatenate two rosters from two different blocks when propagating forward-links so that every conode implied will know about it.

Roster concatenation

---

local.go
overlay.go
server.go
service.go
treenode.go

Some errors were not caught when shutting down the service and Treenodes.
Also the shutdown-logic has been changed to start calling  before shutting down the server.

Catching errors and improving shutdown

---

overlay.go
overlay_test.go
tree.go
tree_test.go

The server can crash if a panic occurs during a protocol execution so this PR adds the missing recover to prevent the crash and log the event.
It also updates how the roster ID is generated to include the service keys. This PR changes the Go part but the Java and Javascript generation needs to be fixed also (even if that doesn't break the tests right away).
Fixes dedis/cothority#1725

Recover panic 1725

---

app/config.go
app/config_test.go

This changes the behaviour to not include the service when it has not
been registered
Fixes dedis/cothority#1736

Ignore unregistered services in ParseCothority

---

simul/platform/cliutils.go
simul/platform/deterlab.go
utils.go

Fixes the deterlab part of dedis/cothority#1763
Tested on deterlab with normal go.mod file and `redirect`.

Cd into modules directory to do go build

---

network/struct.go
tree.go
tree_test.go

This sorts the service identities because it can happen the order
array change when writing/reading toml files. This makes sure it
doesn't impact the final ID.
This issue occurs when checking the roster sent back when creating a genesis block in dedis/cothority#1764

Fix the roster ID generation

---

overlay.go
overlay_test.go
tree.go
treenode.go

Adds an aggregate calculation for the Roster and the TreeNodeInstance, which
comes in handy for drynx.

Service Aggregate calculation

---

network/struct.go
network/struct_test.go
tree.go
tree_test.go

Previously the ServiceAggregate failed because it checked for the presence
of a private key. But for the aggregate key, only the public key is needed.

Correctly calculate ServiceAggregate

---

treestorage.go
treestorage_test.go

After the server is closed, it can still process messages and this triggers the storage to clean some trees which creates again new goroutines that won't be closed. This addresses the scenario.
Note: this fixes a flaky test in dedis/cothority

Fix leaking goroutine in treestorage

---

context.go
context_test.go

It might happen that the append builtin was modifying the inner array and then creating a data race. The modification should not happen anyway so this is fixed by copying the array so that there is only reads.

Fix data race when getting new buckets

---

app/config.go

When using app.LoadConfig to read a private.toml, this patch sets the URL correctly
to https:// if there is a WebSocketTLSCertificateKey field set.

sets the URL when reading private.toml

---

network/router.go
network/router_test.go
network/tcp.go

This fixes a potential infinite loop when an unknown error occurs and
will happen every time the connection is handled. This was causing an
infinite loop in some situation.
Fixes dedis/cothority#1851

Drop connection if an unknown error occurs

---

simul/README.md
simul/build.go
simul/monitor/bucket_stats.go
simul/monitor/bucket_stats_test.go
simul/monitor/measure.go
simul/monitor/measure_test.go
simul/monitor/monitor.go
simul/monitor/monitor_test.go
simul/platform/localhost.go
simul/platform/platform.go
simul/platform/platform_test.go
simul/platform/runsimul.go

This PR adds an optional parameter to simulations to define buckets that will be filled with statistics of a subset of the hosts.
Fixes #543

Statistics split into buckets

---

simul/monitor/measure.go
simul/monitor/measure_test.go
simul/platform/runsimul.go

This fixes the simulation to correctly start bandwidth measures on
every server instead of only the ones with the root and reset the
measure to only get statistics after the initialization phase.
Fixes #550

Simulation: fix measures on multiple servers

---

processor.go
processor_test.go

This makes sure that a handler panic will be recovered so that a
meaningful error message can be sent back instead of an empty error.
Fixes dedis/cothority#1934

Recover panics when processing client requests

---

websocket.go
websocket_test.go

This adds a listener that will allow close message to be received
so that we can shutdown streaming handler when the client closes
the connection.
Fixes #554

Listen for close message for streaming requests

---

log/testutil.go
processor_test.go

Performing tests in some environments sometimes leads to leaked goroutines, which are not easy to fix without modifying an external component. Such a situation came up when integrating the Go Ethereum code into an OmniLedger contract: the Ethereum code starts goroutines to perform some caching of transactions, and it never bothers to terminate them.
As a consequence, `AfterTest()` in `log/testutil` rightfully complains about these leaking goroutines and fails the test. Sometimes one can get away with using `bct.local.Check = onet.CheckNone`, but that is not ideal.
In order to avoid polluting the "known interesting goroutines" in `log/testutil`, this PR adds a function that allows to register specific goroutines to be ignored by `AfterTest()`.

Added AddUserInterestingGoroutine() for AfterTest

---

network/tcp.go
network/tcp_test.go

ByzCoin needs this functionality so that connections errors return early
to avoid stalling.

Add a function to set a dial timeout

---

websocket.go

This prevents situation where the error ends up nil for some errors.
Fixes #558

Fix panic occuring in websocket

---

websocket.go
websocket_test.go

Problem: different methods started using different ways of sending messages in parallel
to more than one websocket-client. Sometimes these methods were even done in
parallel.
Solution: add `SendProtobufParallel` method to onet.Client with a unified interface that allows
the caller to precisely describe how to call the nodes, and reasonable defaults to let
it 'do the right thing'.

SendProtobufParallel

---

overlay.go

When a panic happens, it's useful to know where it actually comes from, not only the protocol, but the line and stack-trace.

Add stack-trace to panic-catcher

---

websocket.go

The mobile nativescript app on iOS doesn't support compression
in the websocket communication.

Don't use compression

---

Makefile
local.go
websocket.go
websocket_test.go

- Fix a race in the closing of the websocket
- Stop contacting other nodes in SendProtobufParallel if one node replied successfully

Racy websocket closing

---

websocket.go
websocket_test.go

This adds a custom decoder when sending in parallel so that messages
can be analyzed and refused (e.g. old block index)
Related to dedis/cothority#2002

Use a custom decoder to refuse a message

---

overlay.go
treestorage.go
treestorage_test.go

It could happen that a pending remove was triggered in the middle
of a protocol instance. This adds a refresh to stop the deletion
until the end of the new PI.
Fixes dedis/cothority#2064

Prevent tree removal for new protocol instances

---

go.mod
pprof.go
server.go
websocket.go

Make the pprof HTTP interface available on the webserver, if and
only if the server admin opts in by setting the environment variable
ONET_ALLOW_PPROF.

Add pprof to onet

---

local.go
websocket.go
websocket_test.go

This fixes a problem introduced by #576, where the websocket
server would be started in HTTP mode instead of TLS mode
as a result of the new certificate reloader.
Fixes #583.

Make websocket start correctly when cert comes from reloader

---

local.go
processor_test.go

A lot of tests using ByzCoin have a bad timing when they call local.CloseAll,
because they have a waiting call to 'AddTransactionAndWait', which then needs to
timeout. Adding a non-failing 'WaitDone' at the beginning of Local.CloseAll
removes most of those problems.

Waiting on Local.CloseAll

---

simul/platform/runsimul.go

The return statement is reached only if error is nil

return nil error on successful registration of processor function

---

network/router.go

In situation where a node is processing a request that needs interactions with other nodes, it
can be stuck as the blocking dispatcher only allows one at a time. This switches to the routine
dispatcher that allows multiple requests to be processed.

Use the routine dispatcher to deserve requests asynchronously

---

Makefile
network/router.go
overlay.go
service_test.go

Closes #610 
This is a much simpler version than #609. Instead of sending two messages serially, which can get two different connections, it extends the signature of `Router.Send` to a variadic number of messages to send.
-> Backwards compatible
-> passes test

simpler solution to the configuration problem

---

app/server.go
network/router.go
overlay.go
processor.go
service.go
simul/monitor/tcpproxy.go
simulation.go
treenode.go
websocket.go

Searched all `/log.*%v/` and `defer` in onet and made sure that:
- all log outputs use `%+v` for errors
- all recover also print the stack-trace

Add traces to errors

---

go.sum
messages.go
overlay.go
overlay_test.go
treenode.go

It fixes the issue where a protocol requiring a configuration could receive a message from a participant (and not the leader) as the first message thus trying to create the protocol with the missing configuration.
Fixes #621

Force protocol config to be sent

---

simul/platform/mininet.go

Closes #627
As this is an important fix and Ceyhun is waiting for it, I propose that once its merged, the version of onet is bumped, and that the new version is included in cothority, and cothority's version also is bumped.

Correctly find mininet directory in GO111MODULE=on

---

websocket.go
websocket_test.go

Weirdly enough, when specifying an `URL` in a conode's config, it doesn't bind the WebSocket tunnel to it, but to the `Address` with its port incremented. This PR fixes that by actually taking `URL` into consideration if `!= ""`.
It will probably **break the servers using `URL` with unspecified port**, such as https://wookiee.ch/conode & https://conode.dedis.ch

websocket: getWSHostPort uses URL if available

---

tracing/logger.go

The first version sent information about GC and memory along every trace.
As this information is quite heavy, it has been moved together with other
information to AddStats, which is only called once per minute.
Reviewers: one OR another

Reducing the size of the honeycomb traces

---

log/loggers.go
log/loggers_test.go
log/lvl.go
log/ui.go

After the tracing addition, DEBUG_LVL=0 produced two outputs per
log-call.
This PR fixes it and adds a test to avoid regression.

Fix logging with DEBUG_LVL=0

---

network/encoding_test.go
network/router.go
network/router_test.go
network/struct.go
network/struct_test.go
network/tcp_test.go

PR failing on purpose (for now).
`ServerIdentity` is not checked for consistency when unmarshaling. As such, one can create an invalid one, send it accross network and it won't be checked when deserializing it, which can yield security issues (unchecked attacker-controlled input).
To fix that, one would implement `encoding.BinaryUnmarshaler`, which I'm trying to do now, but I need some help coding it, if someone has the time :)
So, I'm adding `func (si *ServerIdentity) UnmarshalBinary(data []byte) error`; as I just want to fix ID after most deserialisation is done, I'm trying first to `Unmarshal` or `protobuf.Decode{,WithConstructors}`, which in turn calls `UnmarshalBinary` as it can now be casted to `encoding.BinaryUnmarshaler` :/
And I don't want to redo protobuf decoding by hand, so, …

network/marshal: fix ServerIdentity unmarshalling

---

tracing/README.md
tracing/logger.go
tracing/trace.go
tracing/trace_test.go

By default, don't print the single spans. Also removes a remaining
debug-print. Adds TRACING_DEBUG environmental variable.
OR-review: first one to agree, please merge.

Better tracing defaults

---

tracing/logger.go

The regular statistics didn't include the nodeName.
This PR fixes it.
OR-review - first one to be OK, please merge.

Adding nodename to stats

---

tree.go
tree_test.go

Even though `Roster.ID` is deprecated, it is still used a lot. The `Roster.GetID` method produces hashes that are different from `ID`, so that comparisons between `ID` and `GetID` fail.
As `GetID` is currently only used for `Roster.Equal`, while `ID` is used in many other methods, this PR makes `GetID` behave the same as `ID`.

Roster: Restore `GetID` to same hash as `ID`

---

network/struct.go

the ServerIdentity.Equal method can panic if the given argument
has a nil Point.
This PR makes sure that if any of the variables are nil, the
method Equal returns false.

Improve error handling

---

simul/platform/mininet/install_mininet.sh
simul/platform/mininet/setup_servers.sh
simul/test_simul/count.toml

This includes the possibility to use Ubuntu 18.04 in the
mininet-simulations.
It has been tested on 2 machines on the iccluster with a total
of 400 nodes.

Updating to Ubuntu 18.04

---

network/tcp.go

Warn when a failed connection might be from a known bug

---

context.go
go.mod
go.sum
messages.go
network/encoding.go
network/encoding_test.go
network/struct.go
node_test.go
overlay.go
overlay_test.go
protocol.go
protocol_test.go
server_test.go
service.go
tree.go
websocket_test.go

Replaces the uuid dependency to google/uuid which is actively maintained and uses go.mod
Closes #660

Replace satori/go.uuid with google/uuid

---

network/router.go
server_test.go

The valid peer list should only be applied when receiving new messages.
Sending to any node should always be allowed, as this is something that
comes from the inside, and we suppose that the protocols are correct.
Will need to bump the tag to v3.2.6 for inclusion in cothority

Remove send restriction

---

websocket.go

When a stream is closed by the service itself (such as when the service was streaming progress and finished with a result), it actually errors with "unexpected error: service finished streaming". As it is quite an expected behavior, I'm removing this error and closing the websocket.
It clashes with #670, as we might want to keep the channel opened, anyway, it doesn't change the current behavior of closing the channel when service finishes, just avoid the error.

websocket: do not error on service's close

---

simul/platform/MININET.md
simul/platform/cliutils.go
simul/platform/mininet.go
simul/platform/mininet/install_mininet.sh
simul/platform/mininet/setup_servers.sh
simul/platform/mininet/start.py
simul/test_simul/.gitignore

install_mininet.sh installs for 20.04 from git, because
mininet releases are rarely made now, and because changes were
needed in mininet itself in order to correctly install on 20.04.
These changes were proposed by me and merged into mininet recently,
allowing this work to proceed.
start.py has a critical simplification to use the default
controller. This is required for Mininet on 20.04 to work
at all, and does not stop 14.04 from working. (Others to be tested still.)
Also: Support local development/debugging with VirtualBox,
via NAT port forwarding. (These changes work and are useful, but
are not sufficient to run an entire simulation because the
logging of monitors needs to know the real IP address of the first
server.)

Support Ubuntu 20.04 on platform mininet

---

log/lvl.go

The 'MainTest' method was not aware that 'go test -v' only prints stdout if there was an error.
This PR removes the manual silencing of 'MainTest', allowing a simplified showing of errors, without
having to resort to redirections to a file.
Replaces dedis/cothority#2427

Better logging with go test -v

---

processor.go
processor_test.go

Some streaming services, like the pagination one, use a different stop chan for each call, but the actual implementation would only close the last one, which would lead to go routine leaks.
Cancels https://github.com/dedis/cothority/pull/2437
@ineiti @tharvik: that is related to https://github.com/dedis/cothority/pull/2437. Based on your comments Linus I think the problem should be solved by onet, as I originally did but finally went with the cothority PR. The pagination service should be completely stateless, and onet should ensure it closes all the stop channels.

Updates the processor to close all potential stop chans

---

local.go

While fixing a missing test in byzcoin, I saw that the ServerIdentities are not fully
initialized for local tests. As the new configuration contract in byzcoin also
checks for Address and Description in the ServerIdentity, they also must be
set for local tests.
Once this PR is merged, the onet version should be increased.

Initialize ServerIdentities for local tests
